export const NIGERIAN_STATES = ['Lagos'];

export const LAGOS_LGAS = [
  'Agege',
  'Ajeromi-Ifelodun',
  'Alimosho',
  'Amuwo-Odofin',
  'Apapa',
  'Badagry',
  'Epe',
  'Eti-Osa',
  'Ibeju-Lekki',
  'Ifako-Ijaiye',
  'Ikeja',
  'Ikorodu',
  'Kosofe',
  'Lagos Island',
  'Lagos Mainland',
  'Mushin',
  'Ojo',
  'Oshodi-Isolo',
  'Shomolu',
  'Surulere',
];

export const BUSINESS_SECTORS = [
  'Agriculture & Farming',
  'Automotive',
  'Banking & Finance',
  'Construction & Real Estate',
  'Consulting & Professional Services',
  'Consumer Goods & Retail',
  'Education & Training',
  'Energy & Utilities',
  'Entertainment & Media',
  'Fashion & Apparel',
  'Food & Beverage',
  'Healthcare & Medical',
  'Hospitality & Tourism',
  'ICT (Information & Communication Technology)',
  'Insurance',
  'Legal Services',
  'Logistics & Transportation',
  'Manufacturing',
  'Mining & Natural Resources',
  'Nonprofit & NGOs',
  'Oil & Gas',
  'Pharmaceuticals',
  'Public Sector & Government',
  'Real Estate & Property Development',
  'Security & Safety',
  'Sports & Recreation',
  'Telecommunications',
  'Textile & Leather',
  'Trading & Wholesale',
  'Waste Management & Recycling',
  'Others',
];
